import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const path = resolve('lib/pdf/template.ts');
const content = readFileSync(path, 'utf8');
const lines = content.split('\n');

// Lines 484..1028 (1-indexed) = indices 483..1027 (0-indexed) is the old secSintese
// We'll replace from index 483 to 1027 inclusive

const before = lines.slice(0, 483); // lines 1-483
const after = lines.slice(1028);    // line 1029+

const newSection = `// SECTION 3: SINTESE PRELIMINAR\r
// \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\r
function secSintese(p) {\r
  // generated by patch-sintese.mjs\r
  return '<div>PATCHED</div>';\r
}\r`;

const result = [...before, ...newSection.split('\n'), ...after].join('\n');
writeFileSync(path, result, 'utf8');
console.log('Done. New line count:', result.split('\n').length);
